spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skill_sih
    username: root
    password: ankit
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: skill-service
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
server:
  port: 8089
