server:
  port: 8085

# R2DBC configuration for MySQL
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/job_service_sih
    username: root
    password: ankit
  flyway:
    url: jdbc:mysql://localhost:3306/job_service_sih
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    locations: classpath:db/migration

  application:
    name: JobService

# Eureka client configuration
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}