    CREATE TABLE JOB_PROFILE
    (
        id           INTEGER PRIMARY KEY,
        profile_name VARCHAR(100) NOT NULL
    );

    INSERT INTO JOB_PROFILE (id, profile_name) VALUES
        (1, 'Software Engineer'),
        (2, 'Data Scientist'),
        (3, 'Project Manager'),
        (4, 'UX Designer'),
        (5, 'Network Administrator'),
        (6, 'Business Analyst'),
        (7, 'Marketing Specialist'),
        (8, 'Human Resources Manager'),
        (9, 'Financial Analyst'),
        (10, 'Sales Representative'),
        (11, 'Mechanical Engineer'),
        (12, 'Electrical Engineer'),
        (13, 'Civil Engineer'),
        (14, 'Accountant'),
        (15, 'Lawyer'),
        (16, 'Teacher'),
        (17, 'Nurse'),
        (18, 'Doctor'),
        (19, 'Pharmacist'),
        (20, 'Chef'),
        (21, 'Graphic Designer'),
        (22, 'Content Writer'),
        (23, 'Social Media Manager'),
        (24, 'Customer Service Representative'),
        (25, 'Operations Manager'),
        (26, 'Supply Chain Analyst'),
        (27, 'Quality Assurance Tester'),
        (28, 'Product Manager'),
        (29, 'Systems Analyst'),
        (30, 'Database Administrator'),
        (31, 'Web Developer'),
        (32, 'Mobile App Developer'),
        (33, 'IT Support Specialist'),
        (34, 'Cybersecurity Analyst'),
        (35, 'Machine Learning Engineer'),
        (36, 'Cloud Architect'),
        (37, 'DevOps Engineer'),
        (38, 'Blockchain Developer'),
        (39, 'AI Specialist'),
        (40, 'Environmental Scientist'),
        (41, 'Psychologist'),
        (42, 'Economist'),
        (43, 'Statistician'),
        (44, 'Actuary'),
        (45, 'Real Estate Agent'),
        (46, 'Architect'),
        (47, 'Photographer'),
        (48, 'Journalist'),
        (49, 'Public Relations Specialist'),
        (50, 'Event Planner'),
        (51, 'Hotel Manager'),
        (52, 'Logistics Coordinator'),
        (53, 'Librarian'),
        (54, 'Veterinarian'),
        (55, 'Nutritionist'),
        (56, 'Physical Therapist'),
        (57, 'Paramedic'),
        (58, 'Police Officer'),
        (59, 'Social Worker'),
        (60, 'Translator');